[package]
name = "maple"
version = "0.1.0"
authors = ["Gavin Rossiter <rossiter.gavin@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Simple cross platform renderer and ui toolkit."
repository = "https://github.com/krooq/maple"

[lib]
name = "maple"
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = { path = "../wgpu-rs" }
winit = { version = "0.22.2", features = ["web-sys"] }
futures = "0.3"
# iced_wgpu = { path = "../iced/wgpu" }
# iced_native = { path = "../iced/native" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.12"
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
web-sys = "0.3.40"